{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Simple Automation of Drawing on Autocad using Basic Python "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyautocad import Autocad, APoint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Beam_Drawing.dwg\n"
     ]
    }
   ],
   "source": [
    "acad=Autocad()     ###create_if_not_exists=True\n",
    "\n",
    "print(acad.doc.Name)\n",
    "doc=acad.ActiveDocument\n",
    "ms=doc.ModelSpace"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter no of beam to be drawn : 1\n"
     ]
    }
   ],
   "source": [
    "z=0\n",
    "##Enter no of columns to be drawn\n",
    "N=int(input('Enter no of beam to be drawn : '))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "***********************\n",
      "\n",
      "Beam no 1 \n",
      "Enter length(mm) : 3000\n",
      "Enter breadth(mm) : 230\n",
      "Enter depth(mm) : 300\n",
      "\n",
      "For stirrups : \n",
      "Enter Spacing(mm) on left section(l/3) of Beam : 100\n",
      "Enter Spacing(mm) on center section of Beam  : 150\n",
      "Enter Spacing(mm) on right section(l/3) of Beam  : 100\n",
      "\n",
      "**********Stirrup Diameter***********\n",
      "\n",
      "Enter diameter of stirrup : 8\n",
      "\n",
      "-----------------------------------------------\n",
      "Drawing is Ready Please Check the Autocad\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "for i in range(N):\n",
    "\n",
    "      ##Parameters input\n",
    "    print('***********************')\n",
    "    print('')\n",
    "    print('Beam no {} '.format(i+1))\n",
    "    l=int(input('Enter length(mm) : '))\n",
    "    b=int(input('Enter breadth(mm) : '))\n",
    "    d=int(input('Enter depth(mm) : '))\n",
    "    print('')\n",
    "   \n",
    "    cc=20\n",
    "    column_cc=40\n",
    "    column_width=400\n",
    "      ##Beam dimension with column joint\n",
    "\n",
    "    p1x=[0,0,-column_width,l,l,l+column_width,0,0,0,-24.7,l+24.7,l/6-b/2-17.7,l/6+b/2-17.7,l/6-b/2,l/6-b/2-32.3,l/6-b/2-32.3,l/6-b/2-50]\n",
    "    p1y=[0,d,-500,0,d,-500,0,d,d+425,d+400.2,d+449.7,-492.7,-492.7,-475,-600+17.7,-600+17.7-d,-600]\n",
    "\n",
    "    p2x=[0,0,-column_width,l,l,l+column_width,l,l,l,24.7,l-24.7,l/6-b/2+17.7,l/6+b/2+17.7,l/6+b/2,l/6-b/2-67.7,l/6-b/2-67.7,l/6-b/2-50]\n",
    "    p2y=[-500,d+500,500+d,-500,d+500,500+d,0,d,d+425,d+449.7,d+400.2,-457.3,-457.3,-475,-600-17.7,-600-17.7-d,-600-d]\n",
    "\n",
    "    for j in range(len(p1x)):\n",
    "        p1=APoint(p1x[j],p1y[j]+z)\n",
    "        p2=APoint(p2x[j],p2y[j]+z)\n",
    "        line1=acad.model.AddLine(p1,p2)\n",
    "        line1.layer='Beam_LSection'\n",
    "        if j >= 8:\n",
    "            line1.layer='Text'  \n",
    "    \n",
    "       ##Dimesnions on figure\n",
    "    text_dim=[l,b,d]\n",
    "    ptext_length=APoint(l/2-b/4,d+460+z)\n",
    "    ptext_width=APoint(l/6-b/4,-430+z)\n",
    "    ptext_depth=APoint(l/6-b-100,z-600-d/2)\n",
    "\n",
    "    text_length=acad.model.AddText(' %s'%text_dim[0],ptext_length,30)\n",
    "    text_length.layer='text'\n",
    "\n",
    "    text_width=acad.model.AddText(' %s'%text_dim[1],ptext_width,30)\n",
    "    text_width.layer='text'\n",
    "\n",
    "    text_depth=acad.model.AddText(' %s'%text_dim[2],ptext_depth,30)\n",
    "    text_depth.layer='text'\n",
    "         \n",
    "        #Longitudinal Rebar Top\n",
    "\n",
    "    p3x=[-(column_width-column_cc),-(column_width-column_cc),-(column_width-column_cc),-(column_width-column_cc),l+(column_width-column_cc),l+(column_width-column_cc)]\n",
    "    p3y=[cc,cc,d-cc,d-cc,d-cc,cc,d-cc]\n",
    "\n",
    "    p4x=[l+(column_width-column_cc),-(column_width-column_cc),-(column_width-column_cc),l+(column_width-column_cc),l+(column_width-column_cc),l+(column_width-column_cc)]\n",
    "    p4y=[cc,d+100,-(100),d-cc,-100,d+100]\n",
    "\n",
    "    for k in range(len(p3x)):\n",
    "            p3=APoint(p3x[k],p3y[k]+z)\n",
    "            p4=APoint(p4x[k],p4y[k]+z)\n",
    "            line1= acad.model.AddLine(p3,p4)\n",
    "            line1.layer='Long_rebar'\n",
    "            \n",
    "    ##For stirrups\n",
    "    print('For stirrups : ')\n",
    "    spacing_left=int(input('Enter Spacing(mm) on left section(l/3) of Beam : '))\n",
    "    spacing_center=int(input('Enter Spacing(mm) on center section of Beam  : '))\n",
    "    spacing_right=int(input('Enter Spacing(mm) on right section(l/3) of Beam  : '))\n",
    "        \n",
    "    sp=0\n",
    "            \n",
    "   ##ForStirrups\n",
    "    print('')\n",
    "    print('**********Stirrup Diameter***********')\n",
    "    print('')\n",
    "    stirrup_dia=int(input('Enter diameter of stirrup : '))\n",
    "    for j in range(3):\n",
    "        if j==0:\n",
    "                n_left=round(((l/3-50*2)/spacing_left))+1\n",
    "                 ##Annotation\n",
    "                ##inclined line\n",
    "                ptext_1=APoint(l/6,d/2+z)\n",
    "                ptext_2=APoint(l/6+46.6,-86.4+z)\n",
    "                #Line1\n",
    "                line1=acad.model.AddLine(ptext_1,ptext_2)\n",
    "                line1.layer='text'\n",
    "                ##Flat line\n",
    "                ptext_3=APoint(l/6+46.6,-86.4+z)\n",
    "                ptext_4=APoint(46.6+77+l/6,-86.4+z)\n",
    "                line2=acad.model.AddLine(ptext_3,ptext_4)\n",
    "                line2.layer='text'\n",
    "                ##Text To beshown\n",
    "                text_dim=[n_left,stirrup_dia,spacing_left]\n",
    "                text_length=acad.model.AddText(' %s-%smmdia@%smm c/c'%(text_dim[0],text_dim[1],text_dim[2]),ptext_4,25)\n",
    "                text_length.layer='text'\n",
    "\n",
    "                \n",
    "                ##Stirrup lines @middle\n",
    "                ptext_5=APoint(l/6-250,d/2+z)\n",
    "                ptext_6=APoint(l/6+250,d/2+z)\n",
    "                line3=acad.model.AddLine(ptext_5,ptext_6)\n",
    "                line3.linetype='strrp'\n",
    "                \n",
    "                for j in range(n_left):\n",
    "                    if j == 0:\n",
    "                            p3=APoint(50,cc+z)\n",
    "                            p4=APoint(50,z+d-cc)\n",
    "                            line=acad.model.AddLine(p3,p4)\n",
    "                            line.layer='Stirrups_sides'\n",
    "                            sp=sp+50\n",
    "                           # print(sp)\n",
    "                    else:\n",
    "                            sp=sp+spacing_left\n",
    "                            #print(sp)\n",
    "                            p3=APoint(sp,z+cc)\n",
    "                            p4=APoint(sp,z+d-cc)\n",
    "                            line=acad.model.AddLine(p3,p4)\n",
    "                            line.layer='Stirrups_sides'    \n",
    "         \n",
    "        elif j==1:\n",
    "                n_center=round(((l/3-50*2)/spacing_center))+1\n",
    "                ##inclined line\n",
    "                ptext_1=APoint(l/2,d/2+z)\n",
    "                ptext_2=APoint(46.6+l/2,d+z+86.4)\n",
    "                #Line1\n",
    "                line1=acad.model.AddLine(ptext_1,ptext_2)\n",
    "                line1.layer='text'\n",
    "                ##Flat line\n",
    "                ptext_3=APoint(46.6+l/2,d+z+86.4)\n",
    "                ptext_4=APoint(46.6+77+l/2,d+z+86.4)\n",
    "                line2=acad.model.AddLine(ptext_3,ptext_4)\n",
    "                line2.layer='text'\n",
    "                ##Text To beshown\n",
    "                text_dim=[n_center,stirrup_dia,spacing_center]\n",
    "                text_length=acad.model.AddText(' %s-%smmdia@%smm c/c'%(text_dim[0],text_dim[1],text_dim[2]),ptext_4,25)\n",
    "                text_length.layer='text'\n",
    "                \n",
    "                ##Stirrup lines @middle\n",
    "                ptext_5=APoint(l/2-250,d/2+z)\n",
    "                ptext_6=APoint(l/2+250,d/2+z)\n",
    "                line3=acad.model.AddLine(ptext_5,ptext_6)\n",
    "                line3.linetype='strrp'\n",
    "                \n",
    "                for j in range(n_center):\n",
    "                    sp=sp+spacing_center\n",
    "                    #print(sp)\n",
    "                    p3=APoint(sp,z+cc)\n",
    "                    p4=APoint(sp,z+d-cc)\n",
    "                    line=acad.model.AddLine(p3,p4)\n",
    "                    line.layer='Stirrups_center'         \n",
    "            \n",
    "\n",
    "        else:\n",
    "                n_right=round(((l/3-50*2)/spacing_right))+1\n",
    "                \n",
    "                 ##Annotation\n",
    "                ##inclined line\n",
    "                ptext_1=APoint(5*l/6,d/2+z)\n",
    "                ptext_2=APoint(5*l/6-46.6,-86.4+z)\n",
    "                #Line1\n",
    "                line1=acad.model.AddLine(ptext_1,ptext_2)\n",
    "                line1.layer='text'\n",
    "                ##Flat line\n",
    "                ptext_3=APoint(5*l/6-46.6,-86.4+z)\n",
    "                ptext_4=APoint(5*l/6-46.6-77,-86.4+z)\n",
    "                ptext_5=APoint(5*l/6-46.6-77-468,-86.4+z)\n",
    "                line2=acad.model.AddLine(ptext_3,ptext_4)\n",
    "                line2.layer='text'\n",
    "                ##Text To beshown\n",
    "                text_dim=[n_right,stirrup_dia,spacing_right]\n",
    "                text_length=acad.model.AddText(' %s-%smmdia@%smm c/c'%(text_dim[0],text_dim[1],text_dim[2]),ptext_5,25)\n",
    "                text_length.layer='text'\n",
    "\n",
    "                \n",
    "                ##Stirrup lines @middle\n",
    "                ptext_5=APoint(5*l/6-250,d/2+z)\n",
    "                ptext_6=APoint(5*l/6+250,d/2+z)\n",
    "                line3=acad.model.AddLine(ptext_5,ptext_6)\n",
    "                line3.linetype='strrp'\n",
    "                \n",
    "                \n",
    "                for j in range(n_right):\n",
    "                    sp=sp+spacing_right\n",
    "                   # print(sp)\n",
    "                    if sp>l-50:\n",
    "                        sp=sp-50\n",
    "                        #print(sp)\n",
    "                        #p3=APoint(sp,cc)\n",
    "                        #p4=APoint(sp,d-cc)\n",
    "                        #line=acad.model.Addline(p3,p4)\n",
    "                        #line.layer='Stirrups_sides'\n",
    "                        break\n",
    "                    p3=APoint(sp,z+cc)\n",
    "                    p4=APoint(sp,z+d-cc)\n",
    "                    line=acad.model.AddLine(p3,p4)\n",
    "                    line.layer='Stirrups_sides'            \n",
    "  \n",
    "  #####Section cut line\n",
    "\n",
    "    left_cut=l/6\n",
    "    center_cut=l/2\n",
    "    right_cut=l/2+l/3\n",
    "\n",
    "    section_cutx1=[left_cut,center_cut,right_cut]\n",
    "    section_cuty1=[-300,-300,-300]\n",
    "\n",
    "    section_cutx2=[left_cut,center_cut,right_cut]\n",
    "    section_cuty2=[b+300,b+300,b+300]\n",
    "\n",
    "    text=['A','B','C'] #####\n",
    "\n",
    "    for j in range(len(section_cutx1)):\n",
    "            Cut_line1=APoint(section_cutx1[j],section_cuty1[j]+z)\n",
    "            text1=acad.model.AddText(' %s'%text[j],Cut_line1,50)\n",
    "            text1.layer='text'\n",
    "            Cut_line2=APoint(section_cutx2[j],section_cuty2[j]+z)\n",
    "            text2=acad.model.AddText(' %s'%text[j],Cut_line2,50)\n",
    "            text2.layer='text'\n",
    "            line1=acad.model.AddLine(Cut_line1,Cut_line2)\n",
    "            line1.layer='Section_line'\n",
    "             \n",
    "###Cross Sections\n",
    "##Section AA\n",
    "    p5x=[l/6-(b/2),l/6-(b/2),l/6+(b/2),l/6-(b/2),l/6-(b/2)+cc,l/6-(b/2)+cc,l/6+(b/2)-cc,l/6-(b/2)+cc,l/6-(b/2)+cc+20,l/6-(b/2)+cc,]\n",
    "    p5y=[-600,-(600+d),-600,-600,-600-cc,-(600+d)+cc,-600-cc,-600-cc,-600-cc,-600-cc-20]\n",
    "\n",
    "    p6x=[l/6-(b/2),l/6+(b/2),l/6+(b/2),l/6+(b/2),l/6-(b/2)+cc,l/6+(b/2)-cc,l/6+(b/2)-cc,l/6+(b/2)-cc,l/6-(b/2)+cc+43,l/6-(b/2)+cc+23]\n",
    "    p6y=[-(600+d),-(600+d),-(600+d),-600,-(600+d)+cc,-(600+d)+cc,-(600+d)+cc,-600-cc,-600-cc-23,-600-cc-43]\n",
    "\n",
    "    for i in range(len(p5x)):\n",
    "            Cut_line1=APoint(p5x[i],p5y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line1,50)\n",
    "            Cut_line2=APoint(p6x[i],p6y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line2,50)\n",
    "            line1=acad.model.AddLine(Cut_line1,Cut_line2)\n",
    "            if i <=3:\n",
    "                line1.layer='Beam_CSection'\n",
    "            else:\n",
    "                line1.layer='Stirrups_sides'\n",
    "                       \n",
    "##Rebars    ##\n",
    "##Need to manually enter these values\n",
    "    no_rebar_lower=3\n",
    "    no_rebar_upper=3\n",
    "    dia_rebar_lower=10\n",
    "    dia_rebar_upper=10\n",
    "                          \n",
    "##Section__AA\n",
    "    v_interval=50\n",
    "    text=['SECTION : A-A','SECTION : B-B','SECTION : C-C']\n",
    "    for i in range(2):\n",
    "          \n",
    "                    if i==0:\n",
    "                        ptext=APoint(l/6-b/2,-600-d-150+z)\n",
    "                        text=acad.model.AddText(' %s'%text[i],ptext,30)\n",
    "                        text.layer='text'\n",
    "        ##Lower rebar\n",
    "                        #print('Section AA Lower: ')\n",
    "                        dia_rebar_lower_corner=16#int(input('Corner Bar lower(mm) :'))\n",
    "                              \n",
    "                        sp=l/6-(b/2)+cc+dia_rebar_lower_corner\n",
    "                        spacing=round(b-cc*2-2*dia_rebar_lower)/(no_rebar_lower-1)\n",
    "                        for i in range(no_rebar_lower):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/6,z-600-d-72)\n",
    "                                ptext_5=APoint(l/6+b/2+50,z-600-d-72)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_lower_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                \n",
    "                            elif i == no_rebar_lower-1:\n",
    "                                p_center=APoint(l/6+(b/2)-cc-dia_rebar_lower_corner,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/6,z-600-d-72)\n",
    "                                #ptext_5=APoint(l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_lower_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                #print(sp)\n",
    "                                sp=sp+spacing\n",
    "                                #print(sp)\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower)\n",
    "                                rebar1.layer='rebar_section' \n",
    "                                \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                ptext_5=APoint(l/6+b/2+50,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                \n",
    "                                \n",
    "                                text_dim=[dia_rebar_lower]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "\n",
    "                    elif i==1:\n",
    "                ##Upper rebar\n",
    "                        #print('Section AA Upper: ')\n",
    "                        dia_rebar_upper_corner=16#int(input('Corner Bar Upper(mm) :'))\n",
    "                        sp=l/6-(b/2)+cc+dia_rebar_upper_corner\n",
    "                        spacing=round(b-cc*2-dia_rebar_upper_corner*2)/(no_rebar_upper-1)\n",
    "                        for i in range(no_rebar_upper):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/6,z-500-28)\n",
    "                                ptext_5=APoint(l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_upper_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            elif i == no_rebar_upper-1:\n",
    "                                p_center=APoint(l/6+(b/2)-cc-dia_rebar_upper_corner,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/6,z-500-28)\n",
    "                                #ptext_5=APoint(l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_upper_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                sp=sp+spacing\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                ptext_5=APoint(l/6+b/2+50,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_upper]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "###Cross Sections\n",
    "##Section BB\n",
    "    p5x=[l/2-(b/2),l/2-(b/2),l/2+(b/2),l/2-(b/2),l/2-(b/2)+cc,l/2-(b/2)+cc,l/2+(b/2)-cc,l/2-(b/2)+cc,l/2-(b/2)+cc+20,l/2-(b/2)+cc,]\n",
    "    p5y=[-600,-(600+d),-600,-600,-600-cc,-(600+d)+cc,-600-cc,-600-cc,-600-cc,-600-cc-20]\n",
    "\n",
    "    p6x=[l/2-(b/2),l/2+(b/2),l/2+(b/2),l/2+(b/2),l/2-(b/2)+cc,l/2+(b/2)-cc,l/2+(b/2)-cc,l/2+(b/2)-cc,l/2-(b/2)+cc+43,l/2-(b/2)+cc+23]\n",
    "    p6y=[-(600+d),-(600+d),-(600+d),-600,-(600+d)+cc,-(600+d)+cc,-(600+d)+cc,-600-cc,-600-cc-23,-600-cc-43]\n",
    "\n",
    "    for i in range(len(p5x)):\n",
    "            Cut_line1=APoint(p5x[i],p5y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line1,50)\n",
    "            Cut_line2=APoint(p6x[i],p6y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line2,50)\n",
    "            line1=acad.model.AddLine(Cut_line1,Cut_line2)\n",
    "            if i <=3:\n",
    "                line1.layer='Beam_CSection'\n",
    "            else:\n",
    "                line1.layer='Stirrups_center'\n",
    "    \n",
    "        ##Rebars\n",
    "    no_rebar_lower=3\n",
    "    no_rebar_upper=3\n",
    "    dia_rebar_lower=10\n",
    "    dia_rebar_upper=10\n",
    "                        \n",
    "\n",
    "                          \n",
    "##Section__BB\n",
    "    \n",
    "    text=['SECTION : B-B']\n",
    "    for i in range(2):\n",
    "          \n",
    "                    if i==0:\n",
    "                        ptext=APoint(l/2-b/2,-600-d-150+z)\n",
    "                        text=acad.model.AddText(' %s'%text[i],ptext,30)\n",
    "                        text.layer='text'\n",
    "        ##Lower rebar    \n",
    "                        #print('Section BB Lower: ')\n",
    "                        dia_rebar_lower_corner=16#int(input('Corner Bar Lower(mm) :'))\n",
    "                        sp=l/2-(b/2)+cc+dia_rebar_lower_corner\n",
    "                        spacing=round(b-cc*2-2*dia_rebar_lower_corner)/(no_rebar_lower-1)\n",
    "                        for i in range(no_rebar_lower):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/2,z-600-d-72)\n",
    "                                ptext_5=APoint(l/2+b/2+50,z-600-d-72)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_lower_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                \n",
    "                            elif i == no_rebar_lower-1:\n",
    "                                p_center=APoint(l/2+(b/2)-cc-dia_rebar_lower_corner,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/2,z-600-d-72)\n",
    "                                #ptext_5=APoint(l/2+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_lower_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                sp=sp+spacing\n",
    "                                #print(sp)\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower)\n",
    "                                rebar1.layer='rebar_section' \n",
    "                                \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                ptext_5=APoint(l/2+b/2+50,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                \n",
    "                                \n",
    "                                text_dim=[dia_rebar_lower]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "                    elif i==1:\n",
    "                ##Upper rebar\n",
    "                        #print('Section BB Upper: ')\n",
    "                        dia_rebar_upper_corner=16#int(input('Corner Bar Upper(mm) :'))\n",
    "                        sp=l/2-(b/2)+cc+dia_rebar_upper_corner\n",
    "                        spacing=round(b-cc*2-2*dia_rebar_upper_corner)/(no_rebar_upper-1)\n",
    "                        for i in range(no_rebar_upper):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/2,z-500-28)\n",
    "                                ptext_5=APoint(l/2+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_lower_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            elif i == no_rebar_upper-1:\n",
    "                                p_center=APoint(l/2+(b/2)-cc-dia_rebar_upper_corner,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(l/2,z-500-28)\n",
    "                                #ptext_5=APoint(l/2+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_lower_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                sp=sp+spacing\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                ptext_5=APoint(l/2+b/2+50,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_upper]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "                          \n",
    "                          \n",
    "###Cross Sections\n",
    "##Section CC\n",
    "    p5x=[right_cut-(b/2),right_cut-(b/2),right_cut+(b/2),right_cut-(b/2),right_cut-(b/2)+cc,right_cut-(b/2)+cc,right_cut+(b/2)-cc,right_cut-(b/2)+cc,right_cut-(b/2)+cc+20,right_cut-(b/2)+cc,]\n",
    "    p5y=[-600,-(600+d),-600,-600,-600-cc,-(600+d)+cc,-600-cc,-600-cc,-600-cc,-600-cc-20]\n",
    "\n",
    "    p6x=[right_cut-(b/2),right_cut+(b/2),right_cut+(b/2),right_cut+(b/2),right_cut-(b/2)+cc,right_cut+(b/2)-cc,right_cut+(b/2)-cc,right_cut+(b/2)-cc,right_cut-(b/2)+cc+43,right_cut-(b/2)+cc+23]\n",
    "    p6y=[-(600+d),-(600+d),-(600+d),-600,-(600+d)+cc,-(600+d)+cc,-(600+d)+cc,-600-cc,-600-cc-23,-600-cc-43]\n",
    "\n",
    "    for i in range(len(p5x)):\n",
    "            Cut_line1=APoint(p5x[i],p5y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line1,50)\n",
    "            Cut_line2=APoint(p6x[i],p6y[i]+z)\n",
    "            #acad.model.AddText(' %s'%text[i],Cut_line2,50)\n",
    "            line1=acad.model.AddLine(Cut_line1,Cut_line2)\n",
    "            if i <=3:\n",
    "                line1.layer='Beam_CSection'\n",
    "            else:\n",
    "                line1.layer='Stirrups_sides'\n",
    "    \n",
    "##Rebars\n",
    "    no_rebar_lower=3\n",
    "    no_rebar_upper=3\n",
    "    dia_rebar_lower=10\n",
    "    dia_rebar_upper=10\n",
    "\n",
    "\n",
    "##Section__CC\n",
    "    text=['SECTION : C-C']\n",
    "    for i in range(2):                          \n",
    "            if i==0:\n",
    "                        ptext=APoint(right_cut-b/2,-600-d-150+z)\n",
    "                        text=acad.model.AddText(' %s'%text[i],ptext,30)\n",
    "                        text.layer='text'                          \n",
    "                          \n",
    "##Lower rebar\n",
    "                        #print('Section CC Lower: ')\n",
    "                        dia_rebar_lower_corner=16#int(input('Corner Bar Lower(mm) :'))\n",
    "                        sp=right_cut-(b/2)+cc+dia_rebar_lower_corner\n",
    "                        spacing=round(b-cc*2-2*dia_rebar_lower_corner)/(no_rebar_lower-1)\n",
    "                        for i in range(no_rebar_lower):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(5*l/6,z-600-d-72)\n",
    "                                ptext_5=APoint(5*l/6+b/2+50,z-600-d-72)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_lower_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            elif i == no_rebar_lower-1:\n",
    "                                p_center=APoint(right_cut+(b/2)-cc-dia_rebar_lower_corner,-(600+d)+cc+dia_rebar_lower_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(5*l/6,z-600-d-72)\n",
    "                                #ptext_5=APoint(5*l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_lower_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                sp=sp+spacing\n",
    "                                p_center=APoint(sp,-(600+d)+cc+dia_rebar_lower+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_lower)\n",
    "                                rebar1.layer='rebar_section'     \n",
    "                                \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                ptext_5=APoint(5*l/6+b/2+50,-(600+d)+cc+dia_rebar_lower+z+v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                \n",
    "                                \n",
    "                                text_dim=[dia_rebar_lower]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "                                \n",
    "                          \n",
    "            elif i==1:\n",
    "                ##Upper rebar\n",
    "                        #print('Section CC Upper: ')\n",
    "                        dia_rebar_upper_corner=16#int(input('Corner Bar Upper(mm) :'))\n",
    "                        sp=right_cut-(b/2)+cc+dia_rebar_upper_corner\n",
    "                        spacing=round(b-cc*2-2*dia_rebar_upper_corner)/(no_rebar_upper-1)\n",
    "                        for i in range(no_rebar_upper):\n",
    "                            if i == 0:\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(5*l/6,z-500-28)\n",
    "                                ptext_5=APoint(5*l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_lower_corner]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            elif i == no_rebar_upper-1:\n",
    "                                p_center=APoint(right_cut+(b/2)-cc-dia_rebar_upper_corner,-600-cc-dia_rebar_upper_corner+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper_corner)\n",
    "                                rebar1.layer='rebar_section'\n",
    "                                \n",
    "                                ##For annotation\n",
    "                                ptext_4=APoint(5*l/6,z-500-28)\n",
    "                                #ptext_5=APoint(5*l/6+b/2+50,z-500-28)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                #line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                #text_dim=[dia_rebar_lower_corner]\n",
    "                                #text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                            else:\n",
    "                                sp=sp+spacing\n",
    "                                p_center=APoint(sp,-600-cc-dia_rebar_upper+z)\n",
    "                                rebar1=acad.model.AddCircle(p_center,dia_rebar_upper)\n",
    "                                rebar1.layer='rebar_section'  \n",
    "                                #Annotations\n",
    "                                ptext_4=APoint(sp,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                ptext_5=APoint(5*l/6+b/2+50,-600-cc-dia_rebar_upper+z-v_interval)\n",
    "                                line2=acad.model.AddLine(p_center,ptext_4)\n",
    "                                line3=acad.model.AddLine(ptext_4,ptext_5)\n",
    "                                text_dim=[dia_rebar_upper]\n",
    "                                text_length=acad.model.AddText(' %s mm dia'%(text_dim[0]),ptext_5,20)\n",
    "                                \n",
    "                                #v_interval-=100\n",
    "         \n",
    "        \n",
    "    z=z-4000\n",
    "    print('')\n",
    "    print('-----------------------------------------------')\n",
    "    print('Drawing is Ready Please Check the Autocad')      "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
